### ISSUE TITLE
Add newly created issues to the project

### ISSUE THREAD

**Issue by pauchan** [cookpad/cp8#40]
Whenever issue is created I would like to add it automatically to the given project within repo.
Project name is defined in the payload.

**Comment by balvig** [comment]
Just to confirm, is this different from this built-in feature?

![workflow](https://user-images.githubusercontent.com/104138/41069894-d346d370-6a2a-11e8-8cec-335913be5ef9.png)

**Comment by pauchan** [comment]
☝️ this is unfortunately not what I mean 😭 
The above option move issues added to project automatically to a given column.
What I want to have is trigger to move automatically created issues to project.

**Comment by balvig** [comment]
(Done!)
